name: Release

on:
  push:
    tags: ['[0-9]+\.[0-9]+\.[0-9]+']

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ^1.19

      - name: Create release distribution
        run: make build-all-platforms tar-all-platforms

      - name: Create Github release
        run: |
          export TAG=${GITHUB_REF##*/}
          gh release create ${TAG} --title "Release ${TAG}" *.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
